CC = zcc
AS = z88dk-z80asm
DASM = z88dk-dis
TARGET = m_loader

ASMSRC = $(TARGET).asm
ASMOBJ = $(TARGET).o
BIN = $(TARGET).bin
OBJS = $(ASMOBJ) command_j.o command_d.o command_m.o command_i.o \
	command_b.o command_p.o \
	lcdlib.o \
	command_t.o \
	command_x.o xymodem.o
MAP = $(TARGET).map
ASFLAGS = -DWITH_XYMODEM=1 -DUSE_LCD=1 \
	-DWITH_7SEG=0 -DWITH_SPI=1
CFLAGS = +embedded -DUSE_LCD=1 \
	--opt-code-speed
#	-D__Z88DK_R2L_CALLING_CONVENTION
LDFLAGS = +embedded --no-crt -m 

.PHONY:	all $(OBJS)

all: $(OBJS)
	$(AS) $(ASFLAGS) $(ASMSRC) -o$(ASMOBJ)
	$(CC) $(LDFLAGS) $(OBJS) -o $(BIN)
	$(DASM) -x $(MAP) $(BIN) > $(TARGET).lst

xymodem.o:
	$(CC) $(CFLAGS) -c xymodem.c

lcdlib.o:
	$(CC) $(CFLAGS) -c lcdlib.c

clean:
	rm -f $(BIN) $(OBJS) $(MAP) *.lis *.lst
